name: CI

on: [push]

env:
  version: hterm-1.87

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: clone libapps:${{ env.version }}
        run: git clone -b ${{ env.version }} https://chromium.googlesource.com/apps/libapps
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: build dist
        run: |
          cd libapps
          ./hterm/bin/mkdist
      - name: apply patch
        run: |
          cd libapps/hterm/dist/js
          sed -i 's/var hterm = {};/export const hterm = {};/;s/const lib = {};/export const lib = {};/' hterm_all.js
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist
          path: libapps/hterm/dist/js
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          branch: ${{ env.version }}
          force: true
          directory: libapps/hterm/dist/js
