name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        version: ["1.87"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
      - name: clone libapps:hterm-${{ matrix.version }}
        run: git clone -b hterm-${{ matrix.version }} https://chromium.googlesource.com/apps/libapps
      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
      - name: build dist
        run: |
          cd libapps
          ./hterm/bin/mkdist
      - name: apply patch
        run: |
          mkdir dist
          sed 's/var hterm = {};/export const hterm = {};/;s/const lib = {};/export const lib = {};/' libapps/hterm/dist/js/hterm_all.js > dist/index.mjs
      - name: build package.json
        run: |
          sed 's/VERSION/${{matrix.version}}/' package-template.json > dist/package.json
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dist
          path: dist
      - name: push to branch
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          target_branch: hterm-${{ matrix.version }}
          build_dir: dist
          commit_message: "deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push to npm
        run: |
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
